/**
 * @fileoverview gRPC-Web generated client stub for pubsub_admin
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v5.27.3
// source: pubsub_admin.proto


/* eslint-disable */
// @ts-nocheck


import * as grpcWeb from 'grpc-web';

import * as pubsub_admin_pb from './pubsub_admin_pb'; // proto import: "pubsub_admin.proto"


export class PubSubAdminServiceClient {
  client_: grpcWeb.AbstractClientBase;
  hostname_: string;
  credentials_: null | { [index: string]: string; };
  options_: null | { [index: string]: any; };

  constructor (hostname: string,
               credentials?: null | { [index: string]: string; },
               options?: null | { [index: string]: any; }) {
    if (!options) options = {};
    if (!credentials) credentials = {};
    options['format'] = 'binary';

    this.client_ = new grpcWeb.GrpcWebClientBase(options);
    this.hostname_ = hostname.replace(/\/+$/, '');
    this.credentials_ = credentials;
    this.options_ = options;
  }

  methodDescriptorRequestChannels = new grpcWeb.MethodDescriptor(
    '/pubsub_admin.PubSubAdminService/RequestChannels',
    grpcWeb.MethodType.SERVER_STREAMING,
    pubsub_admin_pb.ChannelRequest,
    pubsub_admin_pb.ChannelResponse,
    (request: pubsub_admin_pb.ChannelRequest) => {
      return request.serializeBinary();
    },
    pubsub_admin_pb.ChannelResponse.deserializeBinary
  );

  requestChannels(
    request: pubsub_admin_pb.ChannelRequest,
    metadata?: grpcWeb.Metadata): grpcWeb.ClientReadableStream<pubsub_admin_pb.ChannelResponse> {
    return this.client_.serverStreaming(
      this.hostname_ +
        '/pubsub_admin.PubSubAdminService/RequestChannels',
      request,
      metadata || {},
      this.methodDescriptorRequestChannels);
  }

}

